name: Script Download dos Diários Oficiais

on:
  schedule:
    - cron: '00 23 * * *' 

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Run Python script
      run: python src/pdf_downloader.py

    - name: Commit and push updated last date
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add --all
        git commit -m "Atualizar última data [skip ci]"
        git push
